# Generated by Django 3.1.2 on 2020-10-20 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image')),
            ],
        ),
    ]
